spring:
  datasource:
    url: jdbc:mysql://bluebox:3306/rentDB?createDatabaseIfNotExist=true
    username: development
    password: development
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

